# Autogenerated wrapper script for log4cplus_jll for i686-linux-gnu-cxx11
export liblog4cplus, liblog4cplusU

JLLWrappers.@generate_wrapper_header("log4cplus")
JLLWrappers.@declare_library_product(liblog4cplus, "liblog4cplus-2.0.so.3")
JLLWrappers.@declare_library_product(liblog4cplusU, "liblog4cplusU-2.0.so.3")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblog4cplus,
        "lib/liblog4cplus.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblog4cplusU,
        "lib/liblog4cplusU.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
