# Autogenerated wrapper script for log4cplus_jll for x86_64-w64-mingw32-cxx11
export liblog4cplus, liblog4cplusU

JLLWrappers.@generate_wrapper_header("log4cplus")
JLLWrappers.@declare_library_product(liblog4cplus, "liblog4cplus-2-0-3.dll")
JLLWrappers.@declare_library_product(liblog4cplusU, "liblog4cplusU-2-0-3.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblog4cplus,
        "bin\\liblog4cplus-2-0-3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblog4cplusU,
        "bin\\liblog4cplusU-2-0-3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
